name: Test

on: push

jobs:
  unit-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Dependencies
      run: npm install
    - name: Run Lint
      run: npm run lint
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright Tests
      run: npm run test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30